name: CBD
on:
  push:
    branches:
      - master
jobs:
  cbd:
    name: doc cbd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn && yarn run deploy
      - name: DeployGP
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist