name: CI
on:
  push:
    branches:
      - master
jobs:
  vue3 demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm install && npm run build
      - name: DeployGP
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
      - name: DeployALiYun
        uses: easingthemes/ssh-deploy@v2
        env:
          ARGS: "-avz --delete"
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "dist"
          TARGET: "/data/apps/DM/dist"